import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>Snippet</title>
      <body className={inter.className}>
        {/* navbar */}
        <nav className="bg-slate-700 text-white p-4">
          <div className="container mx-auto flex justify-between items-center">
            <a href="/" className="text-2xl font-bold">
              Home
            </a>
            <a href="/snippets/new" className="text-blue-500 font-medium">
              Create Snippet
            </a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
